// State metadata for the SEO landing-page generator. Each state gets UNIQUE
// evergreen content (agency, season, context, fire-prone regions, and
// state-specific resources) so the pages are never near-duplicates.
//
// NOTE: `season` strings are interpolated MID-SENTENCE ("…typically runs {season}.")
// — keep them lowercase unless they begin with a proper noun (month names are fine).
export const STATES = [
  { abbr: "CA", name: "California", slug: "california",
    agency: "CAL FIRE", agencyUrl: "https://www.fire.ca.gov/incidents",
    season: "May through October (peaking late summer and fall with offshore winds)",
    blurb: "California sees some of the largest and most destructive wildfires in the United States, driven by prolonged drought, dense fuels, and wind events such as the Santa Ana and Diablo winds. CAL FIRE and federal partners coordinate response across the state's diverse terrain, from coastal ranges to the Sierra Nevada.",
    regions: "Activity concentrates in the Sierra Nevada foothills and the Shasta–Trinity region in the north, the chaparral of Southern California from Ventura to San Diego, and the wildland-urban interface around the Bay Area and wine country. Offshore wind corridors — Santa Ana in the south, Diablo in the north — produce the fastest-moving and most destructive fires.",
    resources: [["https://readyforwildfire.org/", "Ready for Wildfire (CAL FIRE)"], ["https://alertcalifornia.org/", "AlertCalifornia live cameras"]],
    related: ["OR", "NV", "AZ"] },
  { abbr: "OR", name: "Oregon", slug: "oregon",
    agency: "Oregon Department of Forestry", agencyUrl: "https://www.oregon.gov/odf/fire/pages/index.aspx",
    season: "July through September",
    blurb: "Oregon's wildfires range from high-desert rangeland fires east of the Cascades to timber fires in the wetter western forests. East-wind events in late summer can drive rapid fire growth, as seen in recent record seasons.",
    regions: "The Rogue and Umpqua basins of southwest Oregon and the dry forests around Bend and the Deschutes see the most frequent large fires, while the state's biggest smoke events come from timber fires along the Cascade crest. Late-summer east winds can push fires down the western valleys toward populated areas.",
    resources: [["https://wildfire.oregon.gov/", "Oregon wildfire dashboard"], ["https://oregonsmoke.blogspot.com/", "Oregon smoke information"]],
    related: ["WA", "CA", "ID"] },
  { abbr: "WA", name: "Washington", slug: "washington",
    agency: "Washington Department of Natural Resources", agencyUrl: "https://www.dnr.wa.gov/wildfires",
    season: "July through September",
    blurb: "Washington's largest fires typically burn in the shrub-steppe and forests east of the Cascade crest, where hot, dry summers cure grasses and brush. Smoke from these fires frequently affects air quality across the Pacific Northwest.",
    regions: "The Okanogan highlands, Methow Valley, and Columbia Basin account for most of Washington's large fires, with the east slopes of the Cascades close behind. Westside fires are rarer but consequential when east winds align with dry fuels, and eastern-fire smoke regularly reaches the Puget Sound corridor.",
    resources: [["https://wasmoke.blogspot.com/", "Washington smoke information"], ["https://mil.wa.gov/emergency-management-division", "WA Emergency Management"]],
    related: ["OR", "ID", "MT"] },
  { abbr: "ID", name: "Idaho", slug: "idaho",
    agency: "Idaho Department of Lands", agencyUrl: "https://www.idl.idaho.gov/fire-management/",
    season: "July through September",
    blurb: "Much of Idaho is federal and state forest and rangeland, and its remote, rugged terrain produces long-duration wildfires each summer. Lightning is a leading cause of ignitions in the state's backcountry.",
    regions: "The Salmon–Challis backcountry and central Idaho wilderness carry long-duration timber fires that can burn for months, while the Boise foothills and Snake River Plain see fast rangeland fires closer to communities. Many remote fires are managed rather than fully suppressed.",
    resources: [["https://www.idahofireinfo.com/", "Idaho Fire Info"], ["https://www2.deq.idaho.gov/air/", "Idaho air quality (DEQ)"]],
    related: ["MT", "WY", "UT"] },
  { abbr: "MT", name: "Montana", slug: "montana",
    agency: "Montana DNRC", agencyUrl: "https://dnrc.mt.gov/Forestry/Fire-and-Aviation/",
    season: "July through September",
    blurb: "Montana's wildfire season spans expansive grasslands in the east and forested mountains in the west. Dry cold fronts and lightning storms are common ignition drivers across the state's large, sparsely populated landscapes.",
    regions: "Western Montana's Bitterroot and Lolo forests produce the long smoke-heavy timber fires, while the eastern plains see wind-driven grass fires that can cover huge acreage in a day. The Missoula and Flathead valleys often trap smoke during extended August inversions.",
    resources: [["https://www.mtfireinfo.org/", "Montana Fire Info"], ["https://svc.mt.gov/deq/todaysair/", "Montana Today's Air"]],
    related: ["ID", "WY"] },
  { abbr: "WY", name: "Wyoming", slug: "wyoming",
    agency: "Wyoming State Forestry Division", agencyUrl: "https://wsfd.wyo.gov/fire-management",
    season: "June through September",
    blurb: "Wyoming's fires burn across sagebrush rangeland, high plains, and mountain forests. Wind and low humidity can spread grass fires quickly, while beetle-killed timber adds fuel in higher elevations.",
    regions: "Sagebrush basins across central and southwest Wyoming carry fast wind-driven fires, while the Bighorn, Medicine Bow, and Shoshone forests hold heavier timber fuels — including large stands of beetle-killed pine. Fire danger typically peaks after the summer grass cure.",
    resources: [["https://hls.wyo.gov/", "Wyoming Homeland Security"], ["https://www.airnow.gov/state/?name=wyoming", "Wyoming air quality (AirNow)"]],
    related: ["MT", "CO", "UT"] },
  { abbr: "CO", name: "Colorado", slug: "colorado",
    agency: "Colorado Division of Fire Prevention & Control", agencyUrl: "https://dfpc.colorado.gov/sections/wildfire-information-center",
    season: "May through September (with spring wind-driven grass fires)",
    blurb: "Colorado has experienced several of its largest and most damaging wildfires in recent years, including fast-moving grass fires along the Front Range urban interface. High elevation, dry air, and wind make containment challenging.",
    regions: "The Front Range urban interface from Fort Collins to Colorado Springs faces the highest life-and-property risk, while the largest burns have come in the northern mountains and the Western Slope. Downslope wind events can push winter and spring grass fires into neighborhoods with little warning.",
    resources: [["https://www.coemergency.com/", "Colorado Emergency Management"], ["https://www.colorado.gov/airquality/colorado_summary.aspx", "Colorado air quality"]],
    related: ["WY", "UT", "NM"] },
  { abbr: "UT", name: "Utah", slug: "utah",
    agency: "Utah Division of Forestry, Fire & State Lands", agencyUrl: "https://ffsl.utah.gov/fire/",
    season: "June through September",
    blurb: "Utah's wildfires burn across pinyon-juniper, sagebrush, and mountain forests, often ignited by lightning or human activity. Hot, dry summers and steep terrain can drive rapid fire growth in the state's rural counties.",
    regions: "The west desert and central counties — Juab, Millard, Beaver, Iron — carry Utah's big rangeland fires, while the Wasatch and southern mountain forests see steep, terrain-driven timber fires. The Wasatch Front's canyon interface makes even small ignitions consequential near Salt Lake City.",
    resources: [["https://utahfireinfo.gov/", "Utah Fire Info"], ["https://air.utah.gov/", "Utah air quality"]],
    related: ["NV", "AZ", "CO"] },
  { abbr: "NV", name: "Nevada", slug: "nevada",
    agency: "Nevada Division of Forestry", agencyUrl: "https://forestry.nv.gov/",
    season: "June through September",
    blurb: "As the most arid state, Nevada's wildfires are dominated by fast-spreading rangeland and cheatgrass fires that can cover large areas quickly. Invasive grasses have lengthened and intensified the fire season.",
    regions: "Northern Nevada's Great Basin rangelands — especially Elko, Humboldt, and Lincoln counties — see the state's largest cheatgrass-driven fires, while the Sierra Front near Reno and Carson City carries the highest urban-interface risk. Fires here can run tens of thousands of acres in a single burn period.",
    resources: [["https://www.nevadafireinfo.org/", "Nevada Fire Info"], ["https://www.airnow.gov/state/?name=nevada", "Nevada air quality (AirNow)"]],
    related: ["CA", "UT", "AZ"] },
  { abbr: "AZ", name: "Arizona", slug: "arizona",
    agency: "Arizona Department of Forestry & Fire Management", agencyUrl: "https://dffm.az.gov/fire/information",
    season: "April through July (before monsoon season)",
    blurb: "Arizona's wildfire season peaks in the dry, windy period before the summer monsoon. Fires burn across desert grasslands, chaparral, and the ponderosa pine forests of the Mogollon Rim and high country.",
    regions: "The Mogollon Rim country and White Mountains hold the big ponderosa fires, while Sonoran Desert grasslands around Phoenix and Tucson burn fast after wet winters cure into fine fuels. The pre-monsoon June window is historically when Arizona's largest fires make their major runs.",
    resources: [["https://wildlandfire.az.gov/", "Arizona wildland fire info"], ["https://ein.az.gov/", "Arizona Emergency Information Network"]],
    related: ["NM", "UT", "NV"] },
  { abbr: "NM", name: "New Mexico", slug: "new-mexico",
    agency: "New Mexico Forestry Division", agencyUrl: "https://www.emnrd.nm.gov/sfd/",
    season: "April through July",
    blurb: "New Mexico has recorded some of its largest wildfires in history in recent years, driven by extreme spring winds and long-term drought across its mountain forests and grasslands.",
    regions: "The Sangre de Cristo and Jemez mountains in the north and the Gila country in the southwest produce New Mexico's largest forest fires, while eastern plains grasslands carry fast wind-driven fires each spring. Spring wind events routinely gust past 50 mph and dominate fire behavior.",
    resources: [["https://nmfireinfo.com/", "New Mexico Fire Info"], ["https://www.nmdhsem.org/", "NM Homeland Security & Emergency Mgmt"]],
    related: ["AZ", "CO", "TX"] },
  { abbr: "TX", name: "Texas", slug: "texas",
    agency: "Texas A&M Forest Service", agencyUrl: "https://tfsweb.tamu.edu/",
    season: "year-round, peaking in late winter–spring and again in late summer",
    blurb: "Texas experiences wildfires across a wide range of landscapes, from Panhandle grasslands—site of the state's largest recorded fire—to central and east Texas brush. Drought and wind are the primary drivers.",
    regions: "The Panhandle and rolling plains carry the state's largest grass fires — including the million-acre Smokehouse Creek Fire of 2024 — while the Hill Country's juniper-oak brush and east Texas pine see more frequent, smaller fires. Dry frontal passages with strong north winds create the most dangerous days.",
    resources: [["https://ticc.tamu.edu/", "Texas Interagency Coordination Center"], ["https://tdem.texas.gov/", "Texas Division of Emergency Management"]],
    related: ["NM", "OK"] },
  { abbr: "OK", name: "Oklahoma", slug: "oklahoma",
    agency: "Oklahoma Forestry Services", agencyUrl: "https://www.forestry.ok.gov/",
    season: "late winter through spring, with a second peak in late summer",
    blurb: "Oklahoma's wildfires are frequently wind-driven grassland and cross-timbers fires. Low humidity, high winds, and cured vegetation create dangerous fire weather, especially during spring frontal passages.",
    regions: "Western Oklahoma and the Panhandle see the fastest-moving grass fires, while the cross-timbers belt through central Oklahoma mixes grass and oak fuels near more populated areas. Southwest wind events ahead of dry cold fronts produce the state's most dangerous fire days.",
    resources: [["https://okfire.mesonet.org/", "OK-FIRE (Oklahoma Mesonet)"], ["https://oklahoma.gov/oem.html", "Oklahoma Emergency Management"]],
    related: ["TX", "NM", "CO"] },
  { abbr: "AK", name: "Alaska", slug: "alaska",
    agency: "Alaska Division of Forestry & Fire Protection", agencyUrl: "https://forestry.alaska.gov/fire",
    season: "May through August",
    blurb: "Alaska routinely burns more acres than any other state, with vast, remote boreal-forest and tundra fires ignited largely by lightning. Many fires are monitored rather than fully suppressed due to their remote locations.",
    regions: "The Interior between the Alaska Range and the Brooks Range — around Fairbanks, the Yukon Flats, and the Koyukuk — carries the vast majority of burned acreage, almost all of it lightning-ignited boreal forest and tundra. Smoke from Interior fires can blanket Fairbanks for weeks in active seasons.",
    resources: [["https://akfireinfo.com/", "Alaska Wildland Fire Information"], ["https://ready.alaska.gov/", "Alaska emergency preparedness"]],
    related: ["WA", "MT"] },
  { abbr: "FL", name: "Florida", slug: "florida",
    agency: "Florida Forest Service", agencyUrl: "https://www.fdacs.gov/Forest-Wildfire",
    season: "winter through spring (the dry season)",
    blurb: "Florida's wildfires burn in pine flatwoods, palmetto, and swamp during the dry season. Prescribed fire is widely used to reduce fuels, and lightning-ignited fires are common in the state's fire-adapted ecosystems.",
    regions: "The pine flatwoods and palmetto of central and south Florida — and drained swamp margins near the Everglades — burn most often, with dry-season fires occasionally threatening the I-4 and coastal growth corridors. Florida also runs one of the nation's largest prescribed-fire programs, so not all smoke means wildfire.",
    resources: [["https://www.floridadisaster.org/", "Florida Division of Emergency Management"], ["https://www.airnow.gov/state/?name=florida", "Florida air quality (AirNow)"]],
    related: ["TX", "OK"] },
  { abbr: "NE", name: "Nebraska", slug: "nebraska",
    agency: "Nebraska Forest Service", agencyUrl: "https://nfs.unl.edu/wildland-fire",
    season: "spring and late summer",
    blurb: "Nebraska's wildfires are primarily wind-driven grassland fires on the Great Plains, which can grow rapidly under dry, windy conditions. The state's largest fires have burned across the Sandhills and canyon country.",
    regions: "The Sandhills' continuous grass fuels and the pine-studded canyons of the Niobrara valley and Pine Ridge produce Nebraska's largest fires. Spring's cured grass plus strong plains winds — and late-summer drought — define the state's two fire peaks.",
    resources: [["https://nema.nebraska.gov/", "Nebraska Emergency Management"], ["https://www.airnow.gov/state/?name=nebraska", "Nebraska air quality (AirNow)"]],
    related: ["WY", "CO"] },
];

export const STATE_BY_ABBR = Object.fromEntries(STATES.map((s) => [s.abbr, s]));
